export const PoliSiete = () => {
    return (<div>
        <h1 className="text-aonik-3 font-bold text-xl md:text-2xl mb-4 mt-10">Derechos</h1>
        <p className="text-aonik-1 text-sm md:text-base leading-relaxed">
            Los usuarios que faciliten información a través de nuestra página web, como titulares de los datos, tienen derecho a acceder, rectificar, descargar o eliminar su información, así como a restringir y oponerse a determinados tratamientos de su información. Mientras que algunos de estos derechos se aplican de forma general, otros sólo se aplican en determinadas circunstancias limitadas. 
            <br /><br />
            A continuación, describimos estos derechos: Acceso y portabilidad: para acceder y saber qué información está almacenada en nuestros servidores, puede enviarnos su solicitud a través de nuestra información de contacto. Rectificación, restricción, limitación y supresión: También puedes rectificar, restringir, limitar o eliminar gran parte de tu información. Derecho a ser informado: Los usuarios de nuestro sitio web serán informados, si lo solicitan, sobre qué datos recogemos, cómo se utilizan, cuánto tiempo se conservan y si se comparten con terceros. Oposición: Cuando tratemos sus datos basándonos en nuestros intereses legítimos, tal y como se ha explicado anteriormente, o en el interés público, usted podrá oponerse a este tratamiento en determinadas circunstancias. En tales casos, dejaremos de procesar su información a menos que tengamos razones legítimas imperiosas para seguir procesándola o cuando sea necesario por razones legales.Revocar el consentimiento: En los casos en los que haya dado previamente su consentimiento, por ejemplo, para permitirnos procesar y almacenar su información personal, tiene derecho a revocar su consentimiento para el procesamiento y almacenamiento de su información en cualquier momento. Por ejemplo, puede retirar su consentimiento actualizando su configuración. En ciertos casos, podemos seguir procesando su información después de que haya retirado su consentimiento si tenemos una base legal para hacerlo o si su retirada del consentimiento se limitó a ciertas actividades de procesamiento. Reclamación: Si desea presentar una queja sobre el uso que hacemos de su información (y sin perjuicio de cualquier otro derecho que pueda tener), tiene derecho a hacerlo ante la autoridad de control local. Los usuarios pueden ejercer todos estos derechos poniéndose en contacto con nosotros a través de la información de contacto o de la página de contacto. Derechos relacionados con la toma de decisiones automatizada, incluida la elaboración de perfiles: los usuarios del sitio web pueden solicitar que les proporcionemos una copia de las actividades de tratamiento automatizado que realizamos si creen que los datos están siendo tratados de forma ilegal. <br /><br /> Los usuarios pueden ejercer sus derechos en relación con los datos personales que proporcionan a Bankok, en cualquier momento, enviándonos su solicitud a través de nuestra información de contacto y procesaremos y responderemos a su solicitud lo antes posible.
        </p>
    </div>
    );
}