export const PoliCinco = () => {
    return (
        <div>
            <h1 className="tittle-politica text-xl md:text-2xl mb-4 mt-10">Cómo compartimos la información</h1>
            <p className="desc-politica text-sm md:text-base leading-relaxed">
                La información personal de nuestros clientes y usuarios es una parte importante y fundamental de nuestro negocio. En ningún caso venderemos o compartiremos información con terceros que no haya sido previamente autorizada por el usuario, cliente o titular de los datos personales. Compartimos la información de usuarios y clientes única y exclusivamente como se describe a continuación. <br /> <br /> <strong>Proveedores de servicios de terceros.</strong> Utilizamos servicios de terceros para realizar funciones en nuestro sitio web. Algunos ejemplos son: Crear y alojar el sitio web, enviar correos electrónicos, analizar datos (Google Analytics), crear anuncios (Facebook, Google), proporcionar asistencia de marketing y proporcionar resultados de búsqueda.
                <br /><br /> Estos servicios y herramientas de terceros pueden tener acceso a la información personal necesaria para realizar sus funciones, pero no pueden utilizar esa información para otros fines. La información compartida con estos servicios de terceros será tratada y almacenada de acuerdo con sus respectivas políticas de privacidad y nuestra política de privacidad. Consulte la política de privacidad de estos servicios de terceros.
                <br /><br /> <strong>Transferencia de negocios.</strong>  En el caso de que Bankok cree, se fusione o sea adquirida por otra entidad o compañía, su información probablemente será transferida. Bankok le enviará un correo electrónico o publicará un aviso destacado en nuestra plataforma antes de que su información esté sujeta a otra política de privacidad y la transferencia y el manejo de su información privada cumplirá con todos los requisitos aplicables. <br /> <br /> <strong>Protección de Bankok y otros.</strong>  Divulgamos información personal cuando creemos que es apropiado para cumplir con la ley, hacer cumplir o aplicar nuestros Términos y condiciones y otros acuerdos, o proteger los derechos, la propiedad o la seguridad de Bankok, nuestros usuarios u otros. Esto incluye el intercambio de información con otras empresas y organizaciones para la protección contra el fraude y la reducción del riesgo de crédito. <br /><br /> <strong>Con su consentimiento.</strong>  Aparte de lo establecido anteriormente, usted recibirá un aviso cuando la información personal identificable sobre usted pueda ir a terceros, y usted tendrá la oportunidad de elegir no compartir la información. <br /><br /> <strong>Información anónima.</strong> Bankok utiliza la información anónima de navegación recogida automáticamente por nuestros servidores principalmente para ayudarnos a administrar y mejorar el sitio web. También podemos utilizar la información anónima agregada para proporcionar información sobre el sitio web a posibles socios comerciales y otras entidades no afiliadas. Esta información no es personalmente identificable. <br /> <br /> <strong>Dirección de correo electrónico.</strong>  La dirección de correo electrónico que nos proporcione para recibir nuestras comunicaciones por correo electrónico nunca será alquilada ni vendida a terceros.
            </p>
        </div>
    );
}