export const PoliUno = () => {
    return (
        <div>
            <h1 className="tittle-politica text-xl md:text-2xl mb-4 mt-10">Tipos de información recopilada</h1>
            <p className="desc-politica text-sm md:text-base leading-relaxed">
                La información que obtenemos de los clientes ayuda a personalizar y mejorar continuamente su experiencia en Bankok Estos son los tipos de información que recopilamos:
                <br /><br />
                <strong>Información que usted nos proporciona.</strong> Usted proporciona información cuando busca, lee y ve contenido en nuestro sitio web, proporciona información a través de nuestros servicios y/o se comunica con nosotros a través de nuestra información de contacto o nuestros formularios de contacto. Como resultado de esas acciones, usted podría proporcionarnos la siguiente información:
                <br /><br />
                Nombre y apellidos, Número de Cédula, Dirección de correo electrónico, Número de teléfono (incluye el número de WhatsApp), Dirección de domicilio, Dirección IP, Cualquier información adicional relacionada con usted que nos proporcione directamente a través de nuestro sitio web o indirectamente a través de nuestro sitio web o presencia en línea, como las "cookies. Bankok no recogerá ninguna información personal identificable sobre usted, a menos que usted la proporcione.
                <br /><br />Información recopilada automáticamente: Al acceder y utilizar el sitio web usted nos proporciona automáticamente la siguiente información: El dispositivo y la información de uso que utiliza para acceder al sitio web, Su dirección IP, Características del navegador y del dispositivo, Sistema operativo, URL de referencia, Su ubicación, Qué partes del sitio web utiliza y con qué frecuencia.
                <br /><br /> Si accede al sitio web a través de un teléfono móvil, recopilaremos la siguiente información: ID del dispositivo móvil, Modelo y fabricante, Sistema operativo, Información sobre la versión, Dirección IP.
                <br /><br /><strong>GOOGLE Analytics.</strong> Utilizamos Google Analytics proporcionado por Google, Inc. de Estados Unidos ("Google"). Estas herramientas y tecnologías recopilan y analizan determinados tipos de información, como direcciones IP, identificadores de dispositivos y de software, URL de referencia y de salida, métricas y estadísticas de uso de las funciones, historial de uso, dirección de control de acceso a los medios (dirección MAC), identificadores únicos de dispositivos móviles y otra información similar mediante el uso de cookies. La información generada por Google Analytics (incluida su dirección IP) puede ser transmitida y almacenada por Google en servidores de Estados Unidos. Utilizamos la recopilación de datos de GOOGLE Analytics para mejorar el sitio web y nuestro servicio.
                <br /><br /> Consulte la política de privacidad de Google aquí: <b className="text-orange-500">policies google</b> Redes sociales: En nuestro sitio web encontrará enlaces y funciones vinculadas a diferentes redes sociales, donde podrá compartir su información. Es recomendable consultar la política de privacidad de cada red social utilizada en nuestro sitio web. <strong>Facebook:</strong> <b className="text-orange-500">Facebook Privacy </b><strong>Twitter:</strong> <b className="text-orange-500">Twitter Privacy </b><strong>Whatsapp:</strong> <b className="text-orange-500">Whatsapp Privacy</b>
            </p>
        </div>
    );
}